# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

,Unnamed: 0,Month,Day of The Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,reason_1,reason_2,reason_3,reason_4
0,0,7,1,289,36,33,239.554,30,0,2,1,4,0,0,0,1
1,1,7,1,118,13,50,239.554,31,0,1,0,0,0,0,0,0
2,2,7,2,179,51,38,239.554,31,0,0,0,2,0,0,0,1
3,3,7,3,279,5,39,239.554,24,0,2,0,4,1,0,0,0
4,4,7,3,289,36,33,239.554,30,0,2,1,2,0,0,0,1

## Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

,Unnamed: 0,Month,Day of The Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,reason_1,reason_2,reason_3,reason_4,Excessive Absenteeism
0,0,7,1,289,36,33,239.554,30,0,2,1,4,0,0,0,1,1
1,1,7,1,118,13,50,239.554,31,0,1,0,0,0,0,0,0,0
2,2,7,2,179,51,38,239.554,31,0,0,0,2,0,0,0,1,0
3,3,7,3,279,5,39,239.554,24,0,2,0,4,1,0,0,0,1
4,4,7,3,289,36,33,239.554,30,0,2,1,2,0,0,0,1,0

## A comment on the targets

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of The Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

,Unnamed: 0,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,reason_1,reason_2,reason_3,reason_4,Excessive Absenteeism
0,0,7,289,33,30,0,2,1,0,0,0,1,1
1,1,7,118,50,31,0,1,0,0,0,0,0,0
2,2,7,179,38,31,0,0,0,0,0,0,1,0
3,3,7,279,39,24,0,2,0,1,0,0,0,1
4,4,7,289,33,30,0,2,1,0,0,0,1,0

## Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 13)

In [14]:
data_with_targets.iloc[:,:14]

,Unnamed: 0,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,reason_1,reason_2,reason_3,reason_4,Excessive Absenteeism
0,0,7,289,33,30,0,2,1,0,0,0,1,1
1,1,7,118,50,31,0,1,0,0,0,0,0,0
2,2,7,179,38,31,0,0,0,0,0,0,1,0
3,3,7,279,39,24,0,2,0,1,0,0,0,1
4,4,7,289,33,30,0,2,1,0,0,0,1,0
5,5,7,179,38,31,0,0,0,0,0,0,1,0
6,6,7,361,28,27,0,1,4,0,0,0,1,1
7,7,7,260,36,23,0,4,0,0,0,0,1,1
8,8,7,155,34,25,0,2,0,0,0,1,0,1
9,9,7,235,37,29,1,1,1,0,0,0,1,1
10,10,7,260,36,23,0,4,0,1,0,0,0,1
11,11,7,260,36,23,0,4,0,1,0,0,0,1
12,12,7,260,36,23,0,4,0,1,0,0,0,1
13,13,7,179,38,31,0,0,0,1,0,0,0,0
14,14,7,179,38,31,0,0,0,0,0,0,1,1
15,15,7,246,41,23,0,0,0,1,0,0,0,1
16,16,7,179,38,31,0,0,0,0,0,0,1,0
17,17,7,179,38,31,0,0,0,0,0,1,0,1
18,18,7,189,33,25,0,2,2,1,0,0,0,1
19,19,8,248,47,32,0,2,1,0,0,0,1,0
20,20,8,330,28,25,1,0,0,1,0,0,0,1
21,21,8,179,38,31,0,0,0,1,0,0,0,0
22,22,8,361,28,27,0,1,4,1,0,0,0,1
23,23,8,260,36,23,0,4,0,0,0,0,1,1
24,24,8,289,33,30,0,2,1,0,0,1,0,1
25,25,8,361,28,27,0,1,4,0,0,0,1,1
26,26,8,289,33,30,0,2,1,0,0,0,1,0
27,27,8,157,29,22,0,0,0,0,0,0,1,1
28,28,8,289,33,30,0,2,1,0,0,1,0,1
29,29,8,179,38,31,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,670,4,155,34,25,0,2,0,0,0,0,1,1
671,671,4,225,28,24,0,1,2,0,0,1,0,1
672,672,4,118,50,31,0,1,0,1,0,0,0,0
673,673,4,179,30,19,1,0,0,0,0,0,1,0
674,674,5,235,37,29,1,1,1,0,0,0,1,1
675,675,5,225,41,28,1,2,2,0,0,1,0,0
676,676,5,235,32,25,1,0,0,0,0,0,1,0
677,677,5,118,37,28,0,0,0,1,0,0,0,0
678,678,5,235,43,38,0,1,0,0,0,0,1,1
679,679,5,179,30,19,1,0,0,1,0,0,0,0
680,680,5,291,40,25,0,1,1,0,0,0,1,0
681,681,5,225,41,28,1,2,2,1,0,0,0,1
682,682,5,300,43,25,0,2,1,0,0,1,0,1
683,683,5,225,41,28,1,2,2,0,0,0,1,1
684,684,5,179,30,19,1,0,0,0,0,0,1,0
685,685,5,118,50,31,0,1,0,0,0,0,1,0
686,686,5,118,50,31,0,1,0,1,0,0,0,0
687,687,5,118,37,28,0,0,0,0,0,0,1,0
688,688,5,118,50,31,0,1,0,0,0,0,0,0
689,689,5,179,30,19,1,0,0,0,0,0,1,0
690,690,5,378,36,21,0,2,4,0,0,0,0,0
691,691,5,179,40,22,1,2,0,0,1,0,0,0
692,692,5,155,34,25,0,2,0,1,0,0,0,1
693,693,5,235,32,25,1,0,0,1,0,0,0,1
694,694,5,291,40,25,0,1,1,0,0,0,1,1
695,695,5,179,40,22,1,2,0,1,0,0,0,1
696,696,5,225,28,24,0,1,2,1,0,0,0,0
697,697,5,330,28,25,1,0,0,1,0,0,0,1
698,698,5,235,32,25,1,0,0,0,0,0,1,0
699,699,5,291,40,25,0,1,1,0,0,0,1,0

In [15]:
data_with_targets.iloc[:,:-1]

,Unnamed: 0,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,reason_1,reason_2,reason_3,reason_4
0,0,7,289,33,30,0,2,1,0,0,0,1
1,1,7,118,50,31,0,1,0,0,0,0,0
2,2,7,179,38,31,0,0,0,0,0,0,1
3,3,7,279,39,24,0,2,0,1,0,0,0
4,4,7,289,33,30,0,2,1,0,0,0,1
5,5,7,179,38,31,0,0,0,0,0,0,1
6,6,7,361,28,27,0,1,4,0,0,0,1
7,7,7,260,36,23,0,4,0,0,0,0,1
8,8,7,155,34,25,0,2,0,0,0,1,0
9,9,7,235,37,29,1,1,1,0,0,0,1
10,10,7,260,36,23,0,4,0,1,0,0,0
11,11,7,260,36,23,0,4,0,1,0,0,0
12,12,7,260,36,23,0,4,0,1,0,0,0
13,13,7,179,38,31,0,0,0,1,0,0,0
14,14,7,179,38,31,0,0,0,0,0,0,1
15,15,7,246,41,23,0,0,0,1,0,0,0
16,16,7,179,38,31,0,0,0,0,0,0,1
17,17,7,179,38,31,0,0,0,0,0,1,0
18,18,7,189,33,25,0,2,2,1,0,0,0
19,19,8,248,47,32,0,2,1,0,0,0,1
20,20,8,330,28,25,1,0,0,1,0,0,0
21,21,8,179,38,31,0,0,0,1,0,0,0
22,22,8,361,28,27,0,1,4,1,0,0,0
23,23,8,260,36,23,0,4,0,0,0,0,1
24,24,8,289,33,30,0,2,1,0,0,1,0
25,25,8,361,28,27,0,1,4,0,0,0,1
26,26,8,289,33,30,0,2,1,0,0,0,1
27,27,8,157,29,22,0,0,0,0,0,0,1
28,28,8,289,33,30,0,2,1,0,0,1,0
29,29,8,179,38,31,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
670,670,4,155,34,25,0,2,0,0,0,0,1
671,671,4,225,28,24,0,1,2,0,0,1,0
672,672,4,118,50,31,0,1,0,1,0,0,0
673,673,4,179,30,19,1,0,0,0,0,0,1
674,674,5,235,37,29,1,1,1,0,0,0,1
675,675,5,225,41,28,1,2,2,0,0,1,0
676,676,5,235,32,25,1,0,0,0,0,0,1
677,677,5,118,37,28,0,0,0,1,0,0,0
678,678,5,235,43,38,0,1,0,0,0,0,1
679,679,5,179,30,19,1,0,0,1,0,0,0
680,680,5,291,40,25,0,1,1,0,0,0,1
681,681,5,225,41,28,1,2,2,1,0,0,0
682,682,5,300,43,25,0,2,1,0,0,1,0
683,683,5,225,41,28,1,2,2,0,0,0,1
684,684,5,179,30,19,1,0,0,0,0,0,1
685,685,5,118,50,31,0,1,0,0,0,0,1
686,686,5,118,50,31,0,1,0,1,0,0,0
687,687,5,118,37,28,0,0,0,0,0,0,1
688,688,5,118,50,31,0,1,0,0,0,0,0
689,689,5,179,30,19,1,0,0,0,0,0,1
690,690,5,378,36,21,0,2,4,0,0,0,0
691,691,5,179,40,22,1,2,0,0,1,0,0
692,692,5,155,34,25,0,2,0,1,0,0,0
693,693,5,235,32,25,1,0,0,1,0,0,0
694,694,5,291,40,25,0,1,1,0,0,0,1
695,695,5,179,40,22,1,2,0,1,0,0,0
696,696,5,225,28,24,0,1,2,1,0,0,0
697,697,5,330,28,25,1,0,0,1,0,0,0
698,698,5,235,32,25,1,0,0,0,0,0,1
699,699,5,291,40,25,0,1,1,0,0,0,1

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [17]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'Month', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets', 'reason_1',
       'reason_2', 'reason_3', 'reason_4'], dtype=object)

In [20]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Unnamed: 0', 'Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets', 'reason_1',
                      'reason_2', 'reason_3', 'reason_4'],
             copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

,Unnamed: 0,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,reason_1,reason_2,reason_3,reason_4
0,-1.729578,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487,-0.577350,-0.092981,-0.314485,0.821365
1,-1.724629,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.577350,-0.092981,-0.314485,-1.217485
2,-1.719681,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
3,-1.714732,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
4,-1.709783,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487,-0.577350,-0.092981,-0.314485,0.821365
5,-1.704835,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
6,-1.699886,0.182726,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,-0.577350,-0.092981,-0.314485,0.821365
7,-1.694937,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
8,-1.689988,0.182726,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,-0.577350,-0.092981,3.179797,-1.217485
9,-1.685040,0.182726,0.190942,0.091435,0.532229,1,-0.019280,0.268487,-0.577350,-0.092981,-0.314485,0.821365
10,-1.680091,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
11,-1.675142,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
12,-1.670194,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
13,-1.665245,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
14,-1.660296,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
15,-1.655347,0.182726,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
16,-1.650399,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
17,-1.645450,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,3.179797,-1.217485
18,-1.640501,0.182726,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663,1.732051,-0.092981,-0.314485,-1.217485
19,-1.635553,0.468236,0.387122,1.660180,1.237836,0,0.880469,0.268487,-0.577350,-0.092981,-0.314485,0.821365
20,-1.630604,0.468236,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
21,-1.625655,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
22,-1.620706,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,1.732051,-0.092981,-0.314485,-1.217485
23,-1.615758,0.468236,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
24,-1.610809,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487,-0.577350,-0.092981,3.179797,-1.217485
25,-1.605860,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016,-0.577350,-0.092981,-0.314485,0.821365
26,-1.600911,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487,-0.577350,-0.092981,-0.314485,0.821365
27,-1.595963,0.468236,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
28,-1.591014,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487,-0.577350,-0.092981,3.179797,-1.217485
29,-1.586065,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
...,...,...,...,...,...,...,...,...,...,...,...,...
670,1.586065,-0.673803,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
671,1.591014,-0.673803,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.577350,-0.092981,3.179797,-1.217485
672,1.595963,-0.673803,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
673,1.600911,-0.673803,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
674,1.605860,-0.388293,0.190942,0.091435,0.532229,1,-0.019280,0.268487,-0.577350,-0.092981,-0.314485,0.821365
675,1.610809,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663,-0.577350,-0.092981,3.179797,-1.217485
676,1.615758,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
677,1.620706,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
678,1.625655,-0.388293,0.190942,1.032682,2.649049,0,-0.019280,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
679,1.630604,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
680,1.635553,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.577350,-0.092981,-0.314485,0.821365
681,1.640501,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663,1.732051,-0.092981,-0.314485,-1.217485
682,1.645450,-0.388293,1.171843,1.032682,-0.408580,0,0.880469,0.268487,-0.577350,-0.092981,3.179797,-1.217485
683,1.650399,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663,-0.577350,-0.092981,-0.314485,0.821365
684,1.655347,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
685,1.660296,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
686,1.665245,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
687,1.670194,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
688,1.675142,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,-0.577350,-0.092981,-0.314485,-1.217485
689,1.680091,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
690,1.685040,-0.388293,2.348925,-0.065439,-1.349389,0,0.880469,2.843016,-0.577350,-0.092981,-0.314485,-1.217485
691,1.689988,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.577350,10.754844,-0.314485,-1.217485
692,1.694937,-0.388293,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
693,1.699886,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
694,1.704835,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.577350,-0.092981,-0.314485,0.821365
695,1.709783,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
696,1.714732,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,1.732051,-0.092981,-0.314485,-1.217485
697,1.719681,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,1.732051,-0.092981,-0.314485,-1.217485
698,1.724629,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.577350,-0.092981,-0.314485,0.821365
699,1.729578,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487,-0.577350,-0.092981,-0.314485,0.821365

In [26]:
scaled_inputs.shape

(700, 12)

## Split the data into train & test and shuffle

### Import the relevant module

In [27]:
from sklearn.model_selection import train_test_split

### Split

In [28]:
train_test_split(scaled_inputs, targets)

[     Unnamed: 0     Month  Transportation Expense       Age  Body Mass Index  \
 685    1.660296 -0.388293               -1.574681  2.130803         1.002633
 494    0.715090  0.468236                0.568211 -0.065439        -0.878984
 663    1.551424 -0.673803                2.092381 -1.320435         0.061825
 8     -1.689988  0.182726               -1.016322 -0.379188        -0.408580
 41    -1.526681  0.753746               -1.574681  0.091435         0.297027
 192   -0.779424 -0.673803               -1.574681  2.130803         1.002633
 522    0.853654  1.039256                1.036026  0.562059        -0.408580
 71    -1.378219  1.039256                1.036026  0.562059        -0.408580
 544    0.962526  1.324766               -0.654143  0.248310         1.002633
 162   -0.927885 -0.959313                0.387122  1.660180         1.237836
 167   -0.903142 -0.959313               -1.016322 -0.379188        -0.408580
 32    -1.571219  0.468236                0.190942  0.091435         0.532229
 370    0.101449 -1.244823               -0.654143  0.248310         1.002633
 103   -1.219860  1.610276                0.568211 -0.065439        -0.878984
 575    1.115937 -1.530333               -0.654143  0.562059        -1.114186
 193   -0.774475 -0.673803                1.036026  0.562059        -0.408580
 239   -0.546834  0.182726               -1.574681  0.091435         0.297027
 231   -0.586424 -0.102784               -1.574681  2.130803         1.002633
 163   -0.922937 -0.959313                0.568211 -0.065439        -0.878984
 391    0.205372 -0.959313                0.356940  0.718933        -0.878984
 242   -0.531988  0.182726               -1.016322 -0.379188        -0.408580
 653    1.501937 -0.959313                2.213108 -0.849811        -0.408580
 361    0.056910 -1.530333                0.190942  0.091435         0.532229
 665    1.561322 -0.673803                0.190942  0.091435         0.532229
 323   -0.131141  1.324766               -1.016322 -0.379188        -0.408580
 209   -0.695295 -0.388293               -0.578689 -1.477309        -1.349389
 221   -0.635911 -0.102784                2.092381 -1.320435         0.061825
 482    0.655706  0.468236                0.356940  0.718933        -0.878984
 38    -1.541527  0.468236                0.190942  1.817054         1.473038
 359    0.047013 -1.530333               -1.574681  0.091435         0.297027
 ..          ...       ...                     ...       ...              ...
 543    0.957578  1.324766                0.040034 -1.320435        -0.643782
 7     -1.694937  0.182726                0.568211 -0.065439        -0.878984
 235   -0.566629 -0.102784                0.040034 -1.320435        -0.643782
 571    1.096142 -1.530333               -0.654143 -1.006686        -1.819793
 466    0.576526  0.182726                0.568211 -0.065439        -0.878984
 104   -1.214911  1.610276               -1.574681  0.091435         0.297027
 528    0.883347  1.039256                0.190942 -0.692937        -0.408580
 190   -0.789321 -0.673803                0.568211 -0.065439        -0.878984
 130   -1.086244 -1.530333                1.005844 -0.536062         0.767431
 377    0.136090 -1.244823               -0.654143  0.248310         1.002633
 495    0.720039  0.753746                0.356940  0.718933        -0.878984
 412    0.309295 -0.673803               -0.654143  0.248310         1.002633
 548    0.982321  1.324766                1.036026  0.562059        -0.408580
 227   -0.606218 -0.102784                0.356940  0.718933        -0.878984
 122   -1.125834 -1.530333                0.040034 -1.320435        -0.643782
 417    0.334039 -0.673803                1.624567 -1.320435        -0.408580
 216   -0.660654 -0.388293                2.499833  2.130803        -0.643782
 127   -1.101091 -1.530333               -1.574681  0.091435         0.297027
 187   -0.804167 -0.673803                0.356940  0.718933        -0.878984
 101   -1.229757  1.610276                0.190942  0.091435         0.532229
 422    0.358782 -0.673803                0.568211 -0.065439        -0.878984
 89    -1.289142  1.324766               -1.016322 -0.379188        -0.408580
 551    0.997167  1.324766                0.190942  1.032682         2.649049
 652    1.496988 -0.959313                1.005844 -0.536062         0.767431
 126   -1.106039 -1.530333               -1.574681  0.091435         0.297027
 493    0.710142  0.468236                1.036026  0.562059        -0.408580
 516    0.823962  1.039256                2.213108 -0.849811        -0.408580
 210   -0.690347 -0.388293               -1.016322 -0.379188        -0.408580
 570    1.091193 -1.530333               -0.654143 -1.006686        -1.819793
 72    -1.373270  1.039256               -0.654143  0.248310         1.002633

      Education  Children      Pets  reason_1  reason_2  reason_3  reason_4
 685          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 494          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 663          0 -0.019280  2.843016 -0.577350 -0.092981 -0.314485  0.821365
 8            0  0.880469 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 41           0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 192          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 522          0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 71           0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 544          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 162          0  0.880469  0.268487  1.732051 -0.092981 -0.314485 -1.217485
 167          0  0.880469 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 32           1 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 370          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 103          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 575          1  0.880469 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 193          0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 239          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 231          0 -0.019280 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 163          0  2.679969 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 391          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 242          0  0.880469 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 653          0  1.780219 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 361          1 -0.019280  0.268487  1.732051 -0.092981 -0.314485 -1.217485
 665          1 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 323          0  0.880469 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 209          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 221          0 -0.019280  2.843016 -0.577350 -0.092981 -0.314485  0.821365
 482          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 38           0 -0.019280  3.701192 -0.577350 -0.092981 -0.314485  0.821365
 359          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 ..         ...       ...       ...       ...       ...       ...       ...
 543          0 -0.019280  1.126663  1.732051 -0.092981 -0.314485 -1.217485
 7            0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 235          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 571          1 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 466          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 104          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 528          1 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 190          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 130          0  0.880469  0.268487 -0.577350 -0.092981  3.179797 -1.217485
 377          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 495          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 412          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 548          0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485 -1.217485
 227          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 122          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 417          1 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 216          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485 -1.217485
 127          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 187          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 101          1 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 422          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 89           0  0.880469 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 551          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485 -1.217485
 652          0  0.880469  0.268487 -0.577350 -0.092981  3.179797 -1.217485
 126          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 493          0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 516          0  1.780219 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 210          0  0.880469 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 570          1 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 72           0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365

 [525 rows x 12 columns],
      Unnamed: 0     Month  Transportation Expense       Age  Body Mass Index  \
 547    0.977373  1.324766                0.040034 -1.320435        -0.643782
 171   -0.883347 -0.959313                0.040034 -1.320435        -0.643782
 288   -0.304346  0.753746               -0.654143  0.248310         1.002633
 354    0.022269  1.610276                0.568211 -0.065439        -0.878984
 401    0.254859 -0.959313                0.190942  0.091435         0.532229
 111   -1.180270  1.610276                0.356940  0.718933        -0.878984
 344   -0.027218  1.610276                0.568211 -0.065439        -0.878984
 631    1.393065 -0.959313               -0.654143  0.248310         1.002633
 351    0.007423  1.610276               -0.654143  0.248310         1.002633
 597    1.224809 -1.244823               -0.654143  0.248310         1.002633
 175   -0.863552 -0.959313                0.040034 -1.320435        -0.643782
 453    0.512193 -0.102784                0.040034 -1.320435        -0.643782
 269   -0.398372  0.468236               -0.578689 -1.477309        -1.349389
 212   -0.680449 -0.388293                1.005844 -0.536062         0.767431
 395    0.225167 -0.959313                0.190942  0.091435         0.532229
 338   -0.056910  1.324766               -0.654143  0.248310         1.002633
 15    -1.655347  0.182726                0.356940  0.718933        -0.878984
 415    0.324141 -0.673803                2.213108 -0.849811        -0.408580
 477    0.630962  0.182726                0.356940  0.718933        -0.878984
 667    1.571219 -0.673803                0.040034 -1.320435        -0.643782
 322   -0.136090  1.324766                2.348925 -0.065439        -1.349389
 202   -0.729936 -0.673803                0.190942  0.091435         0.532229
 566    1.071398  1.610276                0.040034 -1.320435        -0.643782
 262   -0.433013  0.468236               -0.654143 -1.006686        -1.819793
 699    1.729578 -0.388293                1.036026  0.562059        -0.408580
 88    -1.294091  1.324766                0.040034 -1.320435        -0.643782
 245   -0.517141  0.182726               -0.986140 -1.163560        -1.114186
 304   -0.225167  1.039256                0.190942  1.032682         2.649049
 675    1.610809 -0.388293                0.040034  0.718933         0.297027
 491    0.700244  0.468236                0.356940  0.718933        -0.878984
 ..          ...       ...                     ...       ...              ...
 80    -1.333680  1.324766               -0.654143  0.248310         1.002633
 376    0.131141 -1.244823               -0.654143  0.248310         1.002633
 474    0.616116  0.182726                2.092381 -1.320435         0.061825
 198   -0.749731 -0.673803                1.005844 -0.536062         0.767431
 683    1.650399 -0.388293                0.040034  0.718933         0.297027
 565    1.066450  1.610276               -0.654143 -1.006686        -1.819793
 138   -1.046655 -1.244823                0.356940  0.718933        -0.878984
 69    -1.388116  1.039256                0.040034 -1.320435        -0.643782
 220   -0.640859 -0.102784                0.356940  0.718933        -0.878984
 324   -0.126192  1.324766                0.190942  1.032682         2.649049
 480    0.645808  0.468236               -0.654143  0.248310         1.002633
 454    0.517141 -0.102784               -1.574681  2.130803         1.002633
 455    0.522090 -0.102784               -0.654143  0.248310         1.002633
 427    0.383526 -0.388293                2.213108 -0.849811        -0.408580
 301   -0.240013  1.039256                1.005844 -0.536062         0.767431
 70    -1.383168  1.039256                0.387122  1.660180         1.237836
 433    0.413218 -0.388293               -0.654143  0.562059        -1.114186
 30    -1.581117  0.468236               -0.654143  0.248310         1.002633
 134   -1.066450 -1.530333               -1.574681  0.091435         0.297027
 450    0.497347 -0.102784               -0.654143  0.248310         1.002633
 217   -0.655706 -0.388293               -0.654143  0.248310         1.002633
 615    1.313886 -1.244823               -0.654143  0.248310         1.002633
 229   -0.596321 -0.102784                0.190942  0.091435         0.532229
 618    1.328732 -0.959313               -0.654143  0.248310         1.002633
 261   -0.437962  0.468236                0.688938 -0.536062        -0.408580
 199   -0.744783 -0.673803               -1.016322 -0.379188        -0.408580
 270   -0.393423  0.753746               -0.654143  0.248310         1.002633
 390    0.200423 -0.959313               -1.574681  0.091435         0.297027
 218   -0.650757 -0.388293               -1.574681  2.130803         1.002633
 622    1.348527 -0.959313                0.085306  3.385799        -1.114186

      Education  Children      Pets  reason_1  reason_2  reason_3  reason_4
 547          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 171          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 288          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 354          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 401          1 -0.019280  0.268487 -0.577350 -0.092981  3.179797 -1.217485
 111          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 344          0  2.679969 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 631          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 351          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 597          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 175          0 -0.019280  1.126663  1.732051 -0.092981 -0.314485 -1.217485
 453          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 269          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 212          0  0.880469  0.268487  1.732051 -0.092981 -0.314485 -1.217485
 395          1 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 338          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 15           0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 415          0  1.780219 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 477          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 667          0 -0.019280  1.126663 -0.577350 -0.092981  3.179797 -1.217485
 322          0  0.880469  2.843016  1.732051 -0.092981 -0.314485 -1.217485
 202          1 -0.019280  0.268487  1.732051 -0.092981 -0.314485 -1.217485
 566          0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 262          1 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 699          0 -0.019280  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 88           0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 245          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 304          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 675          1  0.880469  1.126663 -0.577350 -0.092981  3.179797 -1.217485
 491          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 ..         ...       ...       ...       ...       ...       ...       ...
 80           0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 376          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 474          0 -0.019280  2.843016 -0.577350 -0.092981 -0.314485  0.821365
 198          0  0.880469  0.268487 -0.577350 -0.092981  3.179797 -1.217485
 683          1  0.880469  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 565          1 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 138          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 69           0 -0.019280  1.126663 -0.577350 -0.092981 -0.314485  0.821365
 220          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 324          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 480          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 454          0 -0.019280 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 455          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 427          0  1.780219 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 301          0  0.880469  0.268487 -0.577350 -0.092981  3.179797 -1.217485
 70           0  0.880469  0.268487 -0.577350 -0.092981 -0.314485  0.821365
 433          1  0.880469 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 30           0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 134          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 450          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 217          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 615          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 229          1 -0.019280  0.268487  1.732051 -0.092981 -0.314485 -1.217485
 618          0 -0.919030 -0.589690 -0.577350 -0.092981 -0.314485  0.821365
 261          1 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 199          0  0.880469 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 270          0 -0.919030 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 390          0 -0.919030 -0.589690 -0.577350 -0.092981  3.179797 -1.217485
 218          0 -0.019280 -0.589690  1.732051 -0.092981 -0.314485 -1.217485
 622          0  0.880469  0.268487  1.732051 -0.092981 -0.314485 -1.217485

 [175 rows x 12 columns],
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [30]:
print (x_train.shape, y_train.shape)

(560, 12) (560,)

In [31]:
print (x_test.shape, y_test.shape)

(140, 12) (140,)

## Logistic regression with sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

/home/fauzan/Downloads/Anaconda/yes/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
reg.score(x_train,y_train)

0.7839285714285714

### Manually check the accuracy

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [38]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [39]:
np.sum((model_outputs==y_train))

439

In [40]:
model_outputs.shape[0]

560

In [41]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

### Finding the intercept and coefficients

In [42]:
reg.intercept_

array([-0.19112896])

In [43]:
reg.coef_

array([[-0.21330678,  0.14524549,  0.68300095, -0.1871582 ,  0.34246972,
        -0.19767121,  0.36265285, -0.30997392,  2.08188898,  0.34609206,
         1.54141448,  1.32163478]])

In [44]:
unscaled_inputs.columns.values

array(['Unnamed: 0', 'Month', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets', 'reason_1',
       'reason_2', 'reason_3', 'reason_4'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

              Feature name  Coefficient
0               Unnamed: 0    -0.213307
1                    Month     0.145245
2   Transportation Expense     0.683001
3                      Age    -0.187158
4          Body Mass Index     0.342470
5                Education    -0.197671
6                 Children     0.362653
7                     Pets    -0.309974
8                 reason_1     2.081889
9                 reason_2     0.346092
10                reason_3     1.541414
11                reason_4     1.321635

In [47]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              Feature name  Coefficient
0                Intercept    -0.191129
1               Unnamed: 0    -0.213307
2                    Month     0.145245
3   Transportation Expense     0.683001
4                      Age    -0.187158
5          Body Mass Index     0.342470
6                Education    -0.197671
7                 Children     0.362653
8                     Pets    -0.309974
9                 reason_1     2.081889
10                reason_2     0.346092
11                reason_3     1.541414
12                reason_4     1.321635

## Interpreting the coefficients

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

              Feature name  Coefficient  Odds_ratio
0                Intercept    -0.191129    0.826026
1               Unnamed: 0    -0.213307    0.807908
2                    Month     0.145245    1.156323
3   Transportation Expense     0.683001    1.979810
4                      Age    -0.187158    0.829313
5          Body Mass Index     0.342470    1.408422
6                Education    -0.197671    0.820640
7                 Children     0.362653    1.437137
8                     Pets    -0.309974    0.733466
9                 reason_1     2.081889    8.019603
10                reason_2     0.346092    1.413533
11                reason_3     1.541414    4.671193
12                reason_4     1.321635    3.749546

In [50]:
summary_table.sort_values('Odds_ratio', ascending=False)

              Feature name  Coefficient  Odds_ratio
9                 reason_1     2.081889    8.019603
11                reason_3     1.541414    4.671193
12                reason_4     1.321635    3.749546
3   Transportation Expense     0.683001    1.979810
7                 Children     0.362653    1.437137
10                reason_2     0.346092    1.413533
5          Body Mass Index     0.342470    1.408422
2                    Month     0.145245    1.156323
4                      Age    -0.187158    0.829313
0                Intercept    -0.191129    0.826026
6                Education    -0.197671    0.820640
1               Unnamed: 0    -0.213307    0.807908
8                     Pets    -0.309974    0.733466

## Testing the model

In [51]:
reg.score(x_test,y_test)

0.7357142857142858

In [52]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75552031, 0.24447969],
       [0.56720051, 0.43279949],
       [0.39771569, 0.60228431],
       [0.82865746, 0.17134254],
       [0.05080024, 0.94919976],
       [0.36614971, 0.63385029],
       [0.22234776, 0.77765224],
       [0.11322093, 0.88677907],
       [0.75132389, 0.24867611],
       [0.67791034, 0.32208966],
       [0.51775983, 0.48224017],
       [0.20301379, 0.79698621],
       [0.03976709, 0.96023291],
       [0.73187874, 0.26812126],
       [0.26883896, 0.73116104],
       [0.53042122, 0.46957878],
       [0.60924576, 0.39075424],
       [0.48350331, 0.51649669],
       [0.46483076, 0.53516924],
       [0.03295126, 0.96704874],
       [0.65934641, 0.34065359],
       [0.8283575 , 0.1716425 ],
       [0.40754356, 0.59245644],
       [0.41009478, 0.58990522],
       [0.24461256, 0.75538744],
       [0.73512636, 0.26487364],
       [0.53617392, 0.46382608],
       [0.8912575 , 0.1087425 ],
       [0.17272807, 0.82727193],
       [0.82925615, 0.17074385],
       [0.70521897, 0.29478103],
       [0.26321419, 0.73678581],
       [0.25384195, 0.74615805],
       [0.50600506, 0.49399494],
       [0.82940556, 0.17059444],
       [0.37779828, 0.62220172],
       [0.82640308, 0.17359692],
       [0.16380008, 0.83619992],
       [0.59360033, 0.40639967],
       [0.3062768 , 0.6937232 ],
       [0.82929873, 0.17070127],
       [0.59797847, 0.40202153],
       [0.74176648, 0.25823352],
       [0.89422064, 0.10577936],
       [0.16048188, 0.83951812],
       [0.36736441, 0.63263559],
       [0.36046174, 0.63953826],
       [0.65655473, 0.34344527],
       [0.79429043, 0.20570957],
       [0.83127478, 0.16872522],
       [0.48364489, 0.51635511],
       [0.91925145, 0.08074855],
       [0.2620385 , 0.7379615 ],
       [0.77045746, 0.22954254],
       [0.11029208, 0.88970792],
       [0.55717978, 0.44282022],
       [0.09605905, 0.90394095],
       [0.82334632, 0.17665368],
       [0.91063338, 0.08936662],
       [0.90852511, 0.09147489],
       [0.34483641, 0.65516359],
       [0.36377293, 0.63622707],
       [0.75635285, 0.24364715],
       [0.12088332, 0.87911668],
       [0.76824854, 0.23175146],
       [0.66965778, 0.33034222],
       [0.98684193, 0.01315807],
       [0.74909157, 0.25090843],
       [0.20724799, 0.79275201],
       [0.60607408, 0.39392592],
       [0.74968631, 0.25031369],
       [0.92392929, 0.07607071],
       [0.07308724, 0.92691276],
       [0.56494346, 0.43505654],
       [0.40425667, 0.59574333],
       [0.82654897, 0.17345103],
       [0.12218313, 0.87781687],
       [0.20516424, 0.79483576],
       [0.23913908, 0.76086092],
       [0.36869764, 0.63130236],
       [0.78132041, 0.21867959],
       [0.98337092, 0.01662908],
       [0.73984572, 0.26015428],
       [0.1898774 , 0.8101226 ],
       [0.57311896, 0.42688104],
       [0.9008041 , 0.0991959 ],
       [0.20259211, 0.79740789],
       [0.46589791, 0.53410209],
       [0.95056079, 0.04943921],
       [0.26341896, 0.73658104],
       [0.86988135, 0.13011865],
       [0.82273488, 0.17726512],
       [0.78500122, 0.21499878],
       [0.7642959 , 0.2357041 ],
       [0.67837114, 0.32162886],
       [0.10654352, 0.89345648],
       [0.70855025, 0.29144975],
       [0.22301508, 0.77698492],
       [0.78502444, 0.21497556],
       [0.8222715 , 0.1777285 ],
       [0.28898361, 0.71101639],
       [0.26280497, 0.73719503],
       [0.25613104, 0.74386896],
       [0.26437863, 0.73562137],
       [0.51207767, 0.48792233],
       [0.43749963, 0.56250037],
       [0.71495392, 0.28504608],
       [0.10735007, 0.89264993],
       [0.17755359, 0.82244641],
       [0.88481179, 0.11518821],
       [0.99251964, 0.00748036],
       [0.06463258, 0.93536742],
       [0.25940547, 0.74059453],
       [0.66114308, 0.33885692],
       [0.44393579, 0.55606421],
       [0.38133919, 0.61866081],
       [0.11993566, 0.88006434],
       [0.12565089, 0.87434911],
       [0.5261334 , 0.4738666 ],
       [0.65380421, 0.34619579],
       [0.67228763, 0.32771237],
       [0.86042124, 0.13957876],
       [0.18544177, 0.81455823],
       [0.59772468, 0.40227532],
       [0.82533494, 0.17466506],
       [0.63991786, 0.36008214],
       [0.83019346, 0.16980654],
       [0.87511534, 0.12488466],
       [0.22916441, 0.77083559],
       [0.75819157, 0.24180843],
       [0.41460087, 0.58539913],
       [0.79144473, 0.20855527],
       [0.70702198, 0.29297802],
       [0.64186142, 0.35813858],
       [0.72513384, 0.27486616],
       [0.38584204, 0.61415796],
       [0.53910001, 0.46089999],
       [0.60196253, 0.39803747],
       [0.78359586, 0.21640414],
       [0.44884865, 0.55115135]])

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
predicted_proba[:,1]

array([0.24447969, 0.43279949, 0.60228431, 0.17134254, 0.94919976,
       0.63385029, 0.77765224, 0.88677907, 0.24867611, 0.32208966,
       0.48224017, 0.79698621, 0.96023291, 0.26812126, 0.73116104,
       0.46957878, 0.39075424, 0.51649669, 0.53516924, 0.96704874,
       0.34065359, 0.1716425 , 0.59245644, 0.58990522, 0.75538744,
       0.26487364, 0.46382608, 0.1087425 , 0.82727193, 0.17074385,
       0.29478103, 0.73678581, 0.74615805, 0.49399494, 0.17059444,
       0.62220172, 0.17359692, 0.83619992, 0.40639967, 0.6937232 ,
       0.17070127, 0.40202153, 0.25823352, 0.10577936, 0.83951812,
       0.63263559, 0.63953826, 0.34344527, 0.20570957, 0.16872522,
       0.51635511, 0.08074855, 0.7379615 , 0.22954254, 0.88970792,
       0.44282022, 0.90394095, 0.17665368, 0.08936662, 0.09147489,
       0.65516359, 0.63622707, 0.24364715, 0.87911668, 0.23175146,
       0.33034222, 0.01315807, 0.25090843, 0.79275201, 0.39392592,
       0.25031369, 0.07607071, 0.92691276, 0.43505654, 0.59574333,
       0.17345103, 0.87781687, 0.79483576, 0.76086092, 0.63130236,
       0.21867959, 0.01662908, 0.26015428, 0.8101226 , 0.42688104,
       0.0991959 , 0.79740789, 0.53410209, 0.04943921, 0.73658104,
       0.13011865, 0.17726512, 0.21499878, 0.2357041 , 0.32162886,
       0.89345648, 0.29144975, 0.77698492, 0.21497556, 0.1777285 ,
       0.71101639, 0.73719503, 0.74386896, 0.73562137, 0.48792233,
       0.56250037, 0.28504608, 0.89264993, 0.82244641, 0.11518821,
       0.00748036, 0.93536742, 0.74059453, 0.33885692, 0.55606421,
       0.61866081, 0.88006434, 0.87434911, 0.4738666 , 0.34619579,
       0.32771237, 0.13957876, 0.81455823, 0.40227532, 0.17466506,
       0.36008214, 0.16980654, 0.12488466, 0.77083559, 0.24180843,
       0.58539913, 0.20855527, 0.29297802, 0.35813858, 0.27486616,
       0.61415796, 0.46089999, 0.39803747, 0.21640414, 0.55115135])

## Save the model

In [55]:
import pickle

In [56]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)